###############################################################################
#   @package        :   Appliances
#   @description    :   Follow and notify appliances running
#   @url            : https://github.com/basnijholt/home-assistant-config
###############################################################################

######################################################################################
# Binary sensors
######################################################################################
binary_sensor:
  - platform: template
    sensors:
      #
      # if current > 0.2 A and stay over for 5 min else off
      #
      washing_machine:
        friendly_name: Lave Linge
        value_template: "{{ states('sensor.smart_switch_6_electric_consumed_a_2')|float(default=0) > 0.2 }}"
        delay_off:
          minutes: 5
        icon_template: >
          {% if is_state("binary_sensor.washing_machine", "on") %}
          mdi:washing-machine
          {% else %}
          mdi:washing-machine-off
          {% endif %}
      #
      # if current > 0.5 A and stay over for 2 min else off
      #
      dryer_machine:
        friendly_name: Sèche Linge
        value_template: "{{ states('sensor.smart_switch_6_electric_consumed_a')|float(default=0) > 0.5 }}"
        delay_off:
          minutes: 2
        icon_template: >
          {% if is_state("binary_sensor.dryer_machine", "on") %}
          mdi:tumble-dryer
          {% else %}
          mdi:tumble-dryer-off
          {% endif %}
