###############################################################################
#   @package        :   Christmas lights
#   @description    :   Controls Christmas lights
#   @url            :
###############################################################################

######################################################################################
# Booleans
######################################################################################
input_boolean:
  #
  # Controle l'activation et désactivation des automations
  #
  christmas_lights_run:
    name: "Automatisations Noël"

###############################################################################
#                               Automations
###############################################################################

automation:
  #
  # Permet d'activer/desactiver les automations de Noël
  #
  - alias: Noel - Activer/Desactiver Planifications
    trigger:
      - platform: state
        entity_id: input_boolean.christmas_lights_run
    action:
      - service: >
          {% if states('input_boolean.christmas_lights_run') == 'on' %}
            switch.turn_on
          {% else %}
            switch.turn_off
          {% endif %}
        data:
          entity_id:
            - switch.schedule_noel_semaine_sapin
            - switch.schedule_noel_weekend_sapin
