###############################################################################
#   @package        :   Harmony TV Activity Control
#   @description    :   Control Harmony TV Activities
#   @url            :
###############################################################################
homeassistant:
  customize:
    # customize pour homebridge
    media_player.salon_tv:
      friendly_name: TV Salon
      source_list: [Orange, Apple TV, AirPlay]
      device_class: tv

#
# Activités disponibles (Select)
#
input_select:
  #
  # Activités disponibles pour homebridge
  #
  salon_tv_activity:
    name: Salon TV Input
    options:
      - Orange
      - Apple TV
      - AirPlay
      - Power Off
    icon: mdi:remote

#
# Media player. Pratique pour HomeBridge
#
media_player:
  - platform: universal
    name: Salon TV
    attributes:
      state: remote.harmony_hub
      source: input_select.salon_tv_activity
      # Obligatoire, serait mieux avec un booleen
      is_volume_muted: true
    commands:
      # Turn on on lance l'activité Regarder TV
      turn_on:
        service: remote.turn_on
        entity_id: remote.harmony_hub
        data:
          activity: Regarder TV
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony_hub
      # Controle du volume sur l'ampli
      volume_up:
        service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: Onkyo
          command: VolumeUp
      volume_down:
        service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: Onkyo
          command: VolumeDown
      volume_mute:
        service: remote.send_command
        entity_id: remote.harmony_hub
        data:
          device: Onkyo
          command: Mute
      select_source:
        # Selon la sélection dans Homekit: change la source
        service: remote.turn_on
        data_template:
          entity_id: remote.harmony_hub
          activity: >-
            {% if source == 'Orange' %}
              Regarder TV
            {% elif source == 'Apple TV' %}
              Regarder Apple TV
            {% elif source == 'AirPlay' %}
              AppleTV
            {% else %}
              Regarder TV
            {% endif %}
