###############################################################################
#   @package        :   Lights Automations
#   @description    :   Automations for lights
#   @url            :
###############################################################################

###############################################################################
#                               Automations
###############################################################################

automation:
  #
  # Permet d'allumer les leds TV 
  #
  - alias: TV - Allumer leds TV
    trigger:
      - platform: state
        entity_id: media_player.salon_tv
        from: 'off'
        to: 'on'
    action:
      - service: switch.turn_on
        data:
          entity_id:
            - switch.fibaro_wall_plug_e_f_switch

  #
  # Controle lumière Bureau en télétravail 
  # (Non terminé)
  #
#  - alias: Bureau - Allumer ordinateur
#    trigger:
#
#    action:
#      - service: hue.hue_activate_scene
#        data:
#          group_name: "Bureau"
#          scene_name: "Stimulation"
