###############################################################################
#   @package        :   Lights Automations
#   @description    :   Automations for lights
#   @url            :
###############################################################################

###############################################################################
#                               Automations
###############################################################################
sensor:
  - platform: template
    sensors:
      dark_outside:
        friendly_name: Dark Outside
        value_template: >
          {% if (state_attr('sun.sun', 'elevation') | int < -2) %}
            true
          {% elif (state_attr('sun.sun', 'elevation') | int < 1) and (states('sensor.maison_cloud_cover') | int > 80) %}
            true
          {% elif (state_attr('sun.sun', 'elevation') | int < 2) and (states('sensor.maison_cloud_cover') | int > 85) %}
            true
          {% elif (state_attr('sun.sun', 'elevation') | int < 3) and (states('sensor.maison_cloud_cover') | int > 95) %}
            true
          {% else %}
            false
          {% endif %}
