# SpeedTest.net CLI
# https://www.speedtest.net/apps/cli
# Telechargé ici : ttps://install.speedtest.net/app/cli/ookla-speedtest-1.1.1-linux-aarch64.tgz
# installé dans /usr/share/hassio/homeassistant/scripts/3rdparty/speedtest
sensor:
  - platform: command_line
    name: "SpeedTest CLI Data"
    unique_id: speedtest_cli_data
    command: "/config/scripts/3rdparty/speedtest/speedtest --format=json --accept-license --accept-gdpr"
    # Every 4 hours, 60 * 60 * 4 = 21600
    scan_interval: 21600
    command_timeout: 60
    # Summarize results to stay below string limit and convert to JSON
    value_template: >-
      {{ 
        { 
          "ping": value_json.ping.latency, 
          "download": value_json.download.bandwidth, 
          "upload": value_json.upload.bandwidth,
          "servername": value_json.server.name,
          "serverlocation": value_json.server.location,
          "servercountry": value_json.server.country,
        }
        | to_json 
      }}
# SpeedTest.net CLI
template:
  - sensor:
      - name: "SpeedTest CLI Ping"
        unique_id: speedtest_cli_ping
        icon: mdi:speedometer
        # TIME_MILLISECONDS: Final = "ms"
        unit_of_measurement: ms
        state_class: measurement
        state: "{{ (states('sensor.speedtest_cli_data') | from_json).ping | round(2) }}"
        attributes:
          server_name: "{{ (states('sensor.speedtest_cli_data') | from_json).servername }}"
          server_location: "{{ (states('sensor.speedtest_cli_data') | from_json).serverlocation }}"
          server_country: "{{ (states('sensor.speedtest_cli_data') | from_json).servercountry }}"
      - name: "SpeedTest CLI Download"
        unique_id: speedtest_cli_download
        icon: mdi:speedometer
        # DATA_RATE_MEGABITS_PER_SECOND: Final = "Mbit/s"
        unit_of_measurement: Mbit/s
        state_class: measurement
        state: "{{ ((states('sensor.speedtest_cli_data') | from_json).download * 8 / 1000 / 1000) | round(2) }}"
        attributes:
          server_name: "{{ (states('sensor.speedtest_cli_data') | from_json).servername }}"
          server_location: "{{ (states('sensor.speedtest_cli_data') | from_json).serverlocation }}"
          server_country: "{{ (states('sensor.speedtest_cli_data') | from_json).servercountry }}"
      - name: "SpeedTest CLI Upload"
        unique_id: speedtest_cli_upload
        icon: mdi:speedometer
        unit_of_measurement: Mbit/s
        state_class: measurement
        state: "{{ ((states('sensor.speedtest_cli_data') | from_json).upload * 8 / 1000 / 1000) | round(2) }}"
        attributes:
          server_name: "{{ (states('sensor.speedtest_cli_data') | from_json).servername }}"
          server_location: "{{ (states('sensor.speedtest_cli_data') | from_json).serverlocation }}"
          server_country: "{{ (states('sensor.speedtest_cli_data') | from_json).servercountry }}"
