###############################################################################
#   @package        :   SSL
#   @description    :   Supervise SSL et reboot reverse nginx
#   @url            :   https://github.com/home-assistant/hassio-addons/issues/1445
###############################################################################
sensor:
  - platform: template
    sensors:
      cert_expiry:
        friendly_name: 'Cert Expiry'
        value_template: >
          {{ ((as_timestamp(states('sensor.cert_expiry_timestamp')) - as_timestamp(states.sensor.date.last_updated)) / 86400) | int }}
        icon_template: >-
          {% if states('sensor.cert_expiry') | int > 0 %}
            mdi:certificate
          {% else %}
            mdi:certificate-outline
          {% endif %}
        unit_of_measurement: 'days'

###############################################################################
#                               Automations
###############################################################################

automation:
  # Il faut redemarrer Nginx pour appliqer le nouveau certificat
  - alias: "SSL - Timestamp certificat expire"
    id: ssl_certificat_expire
    trigger:
      - platform: time
        at: '03:00:00'
    condition:
      - condition: numeric_state
        entity_id: sensor.cert_expiry
        below: 10
    action:
      - service: hassio.addon_restart
        data:
          addon: core_nginx_proxy
      # - delay: 00:05:00
      # - service: homeassistant.restart
      - service: persistent_notification.create
        data:
          message: 'NGinx proxy redemarré pour activer le nouveau certificat.'
