###############################################################################
#   @package        :   System
#   @description    :   Supervision du système
#   @url            :   https://www.home-assistant.io/integrations/system/
###############################################################################

homeassistant:
  customize:
    sensor.ipv4_publique:
      icon: mdi:ip-network
    sensor.ipv6_publique:
      icon: mdi:ip-network

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: processor_use
      - type: last_boot
      - type: throughput_network_in
        arg: eth0
      - type: throughput_network_out
        arg: eth0
  # Pi Temperature
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001) | round(1) }}"

# permet d'allumer/eteindre les leds du Aeotec Stick
switch:
  - platform: command_line
    switches:
      aeotec_zstick_disco_light:
        friendly_name: "Aeotec Z-Stick Disco Light"
        command_on: 'echo -e -n "\x01\x08\x00\xF2\x51\x01\x01\x05\x01\x50" > /dev/serial/by-id/usb-0658_0200-if00'
        command_off: 'echo -e -n "\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51" > /dev/serial/by-id/usb-0658_0200-if00'
