###############################################################################
#   @package        :   Themes
#   @description    :   Gestion des thèmes
#   @url            :
###############################################################################

###############################################################################
#                               Automations
###############################################################################
automation:
  #
  # Change de theme home assistant selon que le soleil est au dessus ou en dessous de l'horizon
  #
  - alias: "Theme - Change jour/nuit (light/dark)"
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sun.sun
        to: above_horizon
      - platform: state
        entity_id: sun.sun
        to: below_horizon
    action:
      - service_template: frontend.set_theme
        data_template:
          name: default
          mode: >
            {% if states.sun.sun.state == "above_horizon" %}
              light
            {% else %}
              dark
            {% endif %}
