###############################################################################
#   @package        :   Weather
#   @description    :   Informations météo
#   @url            :   https://www.home-assistant.io/integrations/weather/
###############################################################################

#
# Add a sensor to have outside informations
#
sensor:
  - platform: template
    sensors:
      outside_temperature:
        friendly_name: "Température extérieure"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('weather.maison', 'temperature') }}"
