###############################################################################
#   @package        :   XBox
#   @description    :   Control Xbox
#   @url            :
###############################################################################
homeassistant:
  customize:
    # customize pour homebridge
    media_player.xboxone:
      friendly_name: XboxOne
      device_class: tv
