###############################################################################
#   @package        :   XBox
#   @description    :   Control Xbox
#   @url            :
###############################################################################
homeassistant:
  customize:
    # customize pour homebridge
    media_player.xboxone:
      friendly_name: XboxOne
      device_class: tv

sensor:
  - platform: history_stats
    name: In game last 7 days
    entity_id: binary_sensor.pwyk_in_game
    state: 'on'
    end: '{{ now().replace(hour=0, minute=0, second=0) }}'
    duration:
      days: 7

###############################################################################
#                               Automations
###############################################################################

automation:
  #
  # Allumer les lumières si la XBOX est allumée
  # (ici car les automations homekit ne gèrent pas le statut unavailable
  # provoquant des allumages intempestifs)
  - alias: Xbox - Allumer lumières
    trigger:
      - platform: state
        entity_id: media_player.xboxone
        from: 'off'
        to: 'on'
    action:
      - service: scene.turn_on
        target:
          entity_id: scene.xbox_allumer
