###############################################################################
#   @package        :   XBox
#   @description    :   Control Xbox
#   @url            :
###############################################################################
homeassistant:
  customize:
    # customize pour homebridge
    media_player.xboxone_x:
      friendly_name: XboxOne
      device_class: tv

sensor:
  - platform: history_stats
    name: In game last 7 days
    entity_id: binary_sensor.pwyk_in_game
    state: "on"
    end: "{{ now().replace(hour=0, minute=0, second=0) }}"
    duration:
      days: 7
