###############################################################################
#   @package        :   ZWave
#   @description    :   Contol OZW Beta components
#   @url            :   https://www.home-assistant.io/integrations/ozw/
###############################################################################

#
# Binary sensors
#
binary_sensor:
  # Network status / query mqtt
  - platform: mqtt
    name: ozw_network_status
    state_topic: OpenZWave/1/status/
    value_template: >
      {{ "ON" if value_json.Status in ["driverAwakeNodesQueried", "driverAllNodesQueriedSomeDead", "driverAllNodesQueried"] else "OFF" }}
    json_attributes_topic: OpenZWave/1/status/
    device_class: "connectivity"

#
# Sensors
#
sensor:
  # Notifications
  - platform: mqtt
    name: ozw_network_notification
    state_topic: OpenZWave/1/event/notification/
    value_template: "{{ value_json.Event }}"
    json_attributes_topic: OpenZWave/1/event/notification/

#
# Input select
#
input_select:
  # Input select for zwave entities
  zwave_entities:
    name: Zwave Entities
    options:
      - Placeholder
#
# Input number
#
input_number:
  ozw_node_id:
    name: Node ID
    min: 1
    max: 254
    mode: box

###############################################################################
#                               Scripts
###############################################################################
script:
  #
  # Send command via mqtt
  #
  ozw_node_command:
    alias: Send OZW Node Command
    icon: mdi:refresh
    mode: single
    sequence:
      - data_template:
          payload:
            '{{ "{" + "\"node\":" + states(''input_number.ozw_node_id'')|int|string
            + "}" }}'
          topic: OpenZWave/1/command/{{zw_command}}/
        service: mqtt.publish

###############################################################################
#                               Automations
###############################################################################

automation:
  #
  # Update Select list
  #
  - alias: OZW - Update Select List
    trigger:
      - platform: state
        entity_id: binary_sensor.ozw_network_status
        from: "off"
        to: "on"
    action:
      - service: input_select.set_options
        data_template:
          entity_id: input_select.zwave_entities
          options: >-
            [{%- for item in (states | selectattr('attributes.node_id') | unique(attribute='attributes.node_id') | list ) %}
            '{{item.attributes.friendly_name + ' ('+item.attributes.node_id|string+')' }}'{% if not loop.last %}, {% endif %}
            {%- endfor %}]
